#!/bin/bash
ACCOUNT=vungle
APP=labelgun
docker run --rm -it -v "$PWD":/go/src/github.com/$ACCOUNT/$APP -w /go/src/github.com/$ACCOUNT/$APP/ golang:1.4.2-cross sh -c '
go get
for GOOS in darwin; do
  for GOARCH in amd64; do
    echo "Building $GOOS-$GOARCH"
    export GOOS=$GOOS
    export GOARCH=$GOARCH
    go build -o bin/labelgun-$GOOS-$GOARCH
  done
done
'
